#!/usr/bin/env bash
# This script transfers a file from a client to a server using SCP

# Display usage message if less than 4 parameters are passed
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables
FILE_PATH="$1"
SERVER_IP="$2"
USERNAME="$3"
SSH_KEY="$4"

# Transfer file to server using SCP
scp -i "$SSH_KEY" -o StrictHostKeyChecking=no "$FILE_PATH" "$USERNAME@$SERVER_IP":~/

# Check if SCP command was successful
if [ $? -eq 0 ]; then
    echo "File transfer successful"
else
    echo "File transfer failed"
fi

