#!/usr/bin/env bash
# Description: Install and configure Nginx on web-01 server
# Requirements: Nginx to listen on port 80 and return "Holberton School" on root query with curl

# Update package index
apt-get -y update

# Install Nginx
apt-get -y install nginx

# Allow Nginx HTTP traffic
ufw allow 'Nginx HTTP'

# Create default HTML page
echo 'Holberton School' > /var/www/html/index.html

# Start Nginx service
service nginx start

