#!/usr/bin/env bash
# Configure Nginx to have a custom 404 page with the string "Ceci n'est pas une page"

# Update package lists and install Nginx
apt-get update
apt-get install -y nginx

# Create a custom 404 page with the string "Ceci n'est pas une page"
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html

# Configure Nginx default site for custom 404 page
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /usr/share/nginx/html;
    index  index.html index.htm;
    error_page 404 /404.html;
    location = /404.html {
         return 301 https://github.com/Anagha-lin;
    }
}" > /etc/nginx/sites-available/default

# Restart Nginx service to apply changes
service nginx restart

