#!/bin/bash
#install ufw if not already installed
sudo apt update
sudo apt install ufw -y

# Set default incoming policy to deny
sudo ufw default deny incoming

# Allow incoming traffic on ports 22, 80, and 443
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp

# Enable ufw
sudo ufw enable

