#!/usr/bin/env bash
#this script runs the whoami command under the user passed as an argument.

# Check if a username argument is provided
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <username>"
    exit 1
fi

# Assign the username argument to a variable
username="$1"

# Run the whoami command under the specified user
sudo -u "$username" whoami

