#!/usr/bin/env bash
# This script connects to the server using the private key ~/.ssh/school

# Use ssh with the private key and specify the user and server IP
ssh -i ~/.ssh/school ubuntu@54.82.199.163

